openapi: 3.1.0
info:
  title: Runtime Command Execution API
  version: 0.1.0
  description: |
    Conceptual contract that mirrors the shared runtime scheduler used by the editor preview,
    test play mode, and exported builds. The Electron shell and browser clients interact with
    an in-memory implementation of these endpoints.
servers:
  - url: https://local-runtime
    description: Logical endpoint hosted inside the editor runtime bridge
paths:
  /runtime/sessions:
    post:
      summary: Start a runtime session for a project scene
      operationId: startSession
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartSessionRequest'
      responses:
        '201':
          description: Session created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionState'
        '422':
          description: Validation error when scene or command list invalid
  /runtime/sessions/{sessionId}/advance:
    post:
      summary: Execute commands until the next blocking point
      operationId: advanceSession
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdvanceRequest'
      responses:
        '200':
          description: Updated session state after commands ran
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionState'
        '409':
          description: Session busy with pending async commands
  /runtime/sessions/{sessionId}/variables:
    patch:
      summary: Apply variable mutations atomically
      operationId: patchVariables
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VariablePatchRequest'
      responses:
        '200':
          description: Variables updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VariablePatchResponse'
        '404':
          description: Session not found or variable undefined
  /runtime/sessions/{sessionId}/cleanup:
    post:
      summary: Force cleanup of scene-scoped resources
      operationId: cleanupSession
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '202':
          description: Cleanup dispatched
  /runtime/sessions/{sessionId}/diagnostics:
    get:
      summary: Fetch diagnostic log entries for parity checks
      operationId: getDiagnostics
      parameters:
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
        - name: sinceEventId
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Ordered diagnostic events
          content:
            application/json:
              schema:
                type: object
                properties:
                  events:
                    type: array
                    items:
                      $ref: '#/components/schemas/DiagnosticEvent'
components:
  schemas:
    StartSessionRequest:
      type: object
      required:
        - projectId
        - sceneId
        - variables
      properties:
        projectId:
          type: string
        sceneId:
          type: string
        variables:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/VariableValue'
        playbackMode:
          type: string
          enum: [editorPreview, testPlay, exported]
        persistHistory:
          type: boolean
          default: true
    AdvanceRequest:
      type: object
      properties:
        maxCommands:
          type: integer
          minimum: 1
          description: Safety cap for stress testing
    SessionState:
      type: object
      required:
        - sessionId
        - sceneId
        - cursor
        - branchTrail
        - pendingAsync
        - variables
      properties:
        sessionId:
          type: string
        sceneId:
          type: string
        cursor:
          type: integer
        commandCount:
          type: integer
        branchTrail:
          type: array
          items:
            type: string
        pendingAsync:
          type: array
          items:
            type: string
        variables:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/VariableValue'
        sceneScope:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/VariableValue'
        diagnosticsPointer:
          type: string
    VariablePatchRequest:
      type: object
      required:
        - writes
      properties:
        writes:
          type: array
          items:
            type: object
            required: [variableId, value, scope]
            properties:
              variableId:
                type: string
              value:
                $ref: '#/components/schemas/VariableValue'
              scope:
                type: string
                enum: [global, scene, transient]
              commandId:
                type: string
    VariablePatchResponse:
      type: object
      required:
        - variables
      properties:
        variables:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/VariableValue'
        lastWriteOrder:
          type: array
          items:
            type: string
    DiagnosticEvent:
      type: object
      required:
        - id
        - timestamp
        - type
        - payload
      properties:
        id:
          type: string
        timestamp:
          type: string
          format: date-time
        type:
          type: string
          enum: [command-start, command-finish, branch-path, cleanup-done, error]
        payload:
          type: object
    VariableValue:
      oneOf:
        - type: string
        - type: number
        - type: integer
        - type: boolean
